### ISSUE TITLE
Option to add an onclick callback on systemtray.showmessage() [To detect that message pop up has been clicked] 

### ISSUE THREAD

**Issue by Dnitin** [PySimpleGUI/psgtray#8]

**Comment by PySimpleGUI** [comment]
Please post issues in the main PySimpleGUI repo for this.

**Comment by PySimpleGUI** [comment]
I'll add something in the readme to log issues there.

The reason is that the SystemTray API and architecture is the same across all of the ports and projects.

The Wx and Qt ports already have this capability.  When the message is clicked, an event: 
 `EVENT_SYSTEM_TRAY_MESSAGE_CLICKED` is returned from `window.read()`.  The the same mechanism would be used with psgtray.

**Comment by PySimpleGUI** [comment]
Are you aware of any capability that `pystray` provides to support this?  I didn't see anything in the docs/code for that package that would enable this feature.

**Comment by Dnitin** [comment]
I'm not aware if this capability is built into psgtray, I went through the implementation and didn't find anything.
